name: fintech_session_guard
description: "Fintech Investment App â€” Session Hijacking Protection (OWASP + NIST)"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Navigation
  go_router: ^15.1.2

  # Network
  dio: ^5.8.0+1

  # Security
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  device_info_plus: ^11.4.0
  crypto: ^3.0.6

  # Dependency Injection
  get_it: ^8.0.3

  # Functional Programming
  dartz: ^0.10.1

  # UI
  google_fonts: ^6.2.1
  fl_chart: ^1.0.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  gap: ^3.0.1
  cached_network_image: ^3.4.1

  # Utils
  uuid: ^4.5.1
  logger: ^2.5.0
  pinput: ^6.0.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
